GET http://localhost:5000/api/auth


###

POST http://localhost:5000/api/auth
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjY0NzE0MzRiM2EwZGU4ODRkMWM4ZjkiLCJpYXQiOjE3MjAyODI1NDEsImV4cCI6MTcyMDI4MjYwMX0.86lG-Qo690-wjYcXMYLq3RG-SU9tzQSb68_TB1YaeaU

###

POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "email": "nguyentuan22072004@gmail.com",
  "password": "tuan",
  "firstname": "tuan",
  "lastname": "nguyen",
  "address": {
    "country": "vietnam",
    "city": "ha noi",
    "province": "dong anh",
    "detail": "xom nguyen"
  }
}

###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "nguyentuan22072004@gmail.com",
  "password": "tuan"
}

###

POST http://localhost:5000/api/auth/token
Content-Type: application/json

{
    "refreshToken" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjY0NzE0MzRiM2EwZGU4ODRkMWM4ZjkiLCJpYXQiOjE3MjE2MjI3ODIsImV4cCI6MTcyMTcwOTE4Mn0.ISaAgzbRm6AvWFwdm_npFDJ0x_He9cl3EBSHksVe87A"
}

###
DELETE http://localhost:5000/api/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjY0NzE0MzRiM2EwZGU4ODRkMWM4ZjkiLCJpYXQiOjE3MjA0MzE1MjksImV4cCI6MTcyMDQzMTU4OX0.f4XrKIBv0NEDTByQya6nsL2SrqzN3enZy4rUZmC1djw

###

POST http://localhost:5000/api/cart
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjY0NzE0MzRiM2EwZGU4ODRkMWM4ZjkiLCJpYXQiOjE3MjA3NzQ0MjEsImV4cCI6MTcyMDc3NDQ4MX0.WjaRWvEWUukXG4M4X0n8Hi0tOCpFxDZuvKVMuRIuAVM
###

GET http://localhost:5000/api/cart
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjY0NzE0MzRiM2EwZGU4ODRkMWM4ZjkiLCJpYXQiOjE3MjA3NzQ0MjEsImV4cCI6MTcyMDc3NDQ4MX0.WjaRWvEWUukXG4M4X0n8Hi0tOCpFxDZuvKVMuRIuAVM

###

PUT http://localhost:5000/api/cart
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjY0NzE0MzRiM2EwZGU4ODRkMWM4ZjkiLCJpYXQiOjE3MjAxMjQwOTksImV4cCI6MTcyMDEyNDE1OX0.bYwyJjtXNp49Wg7WXh2rdSLiOvZa07E9PaYzzVqwT_M

{
  "products":   [
    {
      "id": 1,
      "quantity": 2,
      "size": "S"
    },
    {
      "id": 2,
      "quantity": 2,
      "size": "S"
    },
    {
      "id": 4,
      "quantity": 11,
      "size": "S"
    }
  ]
}

###
DELETE http://localhost:5000/api/cart
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjY0NzE0MzRiM2EwZGU4ODRkMWM4ZjkiLCJpYXQiOjE3MTc5NDk2NTksImV4cCI6MTcxNzk1MzI1OX0.JBeTrWkwlrm5nRmKbNbE8DUK52-cxPrBA9u_sS1Nilo


### 

GET http://localhost:5000/api/order


###
POST http://localhost:5000/api/order
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjY0NzE0MzRiM2EwZGU4ODRkMWM4ZjkiLCJpYXQiOjE3MjA2MDA0NjcsImV4cCI6MTcyMDYwMDUyN30.qmDNaNUH3L4pJy_TIg_gPcA3qrLckEfAkL2MZ6pSL0s

{
  "payment": "CASH",
  "phonenumber" : "0999999",
  "name" : "Tuan anh",
  "email": "adsfads@gmail.com",
  "address": {
    "country": "vietnam",
    "city": "ha noi",
    "province": "dong anh",
    "detail": "xom nguyen"
  },
  "products": [
    {
      "id": 84,
      "title": "Gigabyte Aorus Men Tshirt",
      "description": "The Gigabyte Aorus Men Tshirt is a cool and casual shirt for gaming enthusiasts. With the Aorus logo and sleek design, it's perfect for expressing your gaming style.",
      "category": "mens-shirts",
      "price": 24.99,
      "discountPercentage": 12.6,
      "rating": 4.95,
      "stock": 64,
      "tags": [
        "clothing",
        "men's t-shirts"
      ],
      "brand": "Gigabyte",
      "sku": "QA703Y60",
      "weight": 2,
      "dimensions": {
        "width": 8.54,
        "height": 23.52,
        "depth": 5.66
      },
      "warrantyInformation": "1 month warranty",
      "shippingInformation": "Ships in 1 week",
      "availabilityStatus": "In Stock",
      "reviews": [
        {
          "rating": 4,
          "comment": "Highly recommended!",
          "date": "2024-05-23T08:56:21.623Z",
          "reviewerName": "Logan Lawson",
          "reviewerEmail": "logan.lawson@x.dummyjson.com"
        },
        {
          "rating": 4,
          "comment": "Great value for money!",
          "date": "2024-05-23T08:56:21.623Z",
          "reviewerName": "Logan Lawson",
          "reviewerEmail": "logan.lawson@x.dummyjson.com"
        },
        {
          "rating": 5,
          "comment": "Great value for money!",
          "date": "2024-05-23T08:56:21.623Z",
          "reviewerName": "Oscar Powers",
          "reviewerEmail": "oscar.powers@x.dummyjson.com"
        }
      ],
      "returnPolicy": "30 days return policy",
      "minimumOrderQuantity": 4,
      "meta": {
        "createdAt": "2024-05-23T08:56:21.623Z",
        "updatedAt": "2024-05-23T08:56:21.623Z",
        "barcode": "3072645939073",
        "qrCode": "https://assets.dummyjson.com/public/qr-code.png"
      },
      "images": [
        "https://cdn.dummyjson.com/products/images/mens-shirts/Gigabyte%20Aorus%20Men%20Tshirt/1.png",
        "https://cdn.dummyjson.com/products/images/mens-shirts/Gigabyte%20Aorus%20Men%20Tshirt/2.png",
        "https://cdn.dummyjson.com/products/images/mens-shirts/Gigabyte%20Aorus%20Men%20Tshirt/3.png",
        "https://cdn.dummyjson.com/products/images/mens-shirts/Gigabyte%20Aorus%20Men%20Tshirt/4.png"
      ],
      "thumbnail": "https://cdn.dummyjson.com/products/images/mens-shirts/Gigabyte%20Aorus%20Men%20Tshirt/thumbnail.png",
      "qty": 1,
      "size": 3
    },
    {
      "id": 84,
      "title": "Gigabyte Aorus Men Tshirt",
      "description": "The Gigabyte Aorus Men Tshirt is a cool and casual shirt for gaming enthusiasts. With the Aorus logo and sleek design, it's perfect for expressing your gaming style.",
      "category": "mens-shirts",
      "price": 24.99,
      "discountPercentage": 12.6,
      "rating": 4.95,
      "stock": 64,
      "tags": [
        "clothing",
        "men's t-shirts"
      ],
      "brand": "Gigabyte",
      "sku": "QA703Y60",
      "weight": 2,
      "dimensions": {
        "width": 8.54,
        "height": 23.52,
        "depth": 5.66
      },
      "warrantyInformation": "1 month warranty",
      "shippingInformation": "Ships in 1 week",
      "availabilityStatus": "In Stock",
      "reviews": [
        {
          "rating": 4,
          "comment": "Highly recommended!",
          "date": "2024-05-23T08:56:21.623Z",
          "reviewerName": "Logan Lawson",
          "reviewerEmail": "logan.lawson@x.dummyjson.com"
        },
        {
          "rating": 4,
          "comment": "Great value for money!",
          "date": "2024-05-23T08:56:21.623Z",
          "reviewerName": "Logan Lawson",
          "reviewerEmail": "logan.lawson@x.dummyjson.com"
        },
        {
          "rating": 5,
          "comment": "Great value for money!",
          "date": "2024-05-23T08:56:21.623Z",
          "reviewerName": "Oscar Powers",
          "reviewerEmail": "oscar.powers@x.dummyjson.com"
        }
      ],
      "returnPolicy": "30 days return policy",
      "minimumOrderQuantity": 4,
      "meta": {
        "createdAt": "2024-05-23T08:56:21.623Z",
        "updatedAt": "2024-05-23T08:56:21.623Z",
        "barcode": "3072645939073",
        "qrCode": "https://assets.dummyjson.com/public/qr-code.png"
      },
      "images": [
        "https://cdn.dummyjson.com/products/images/mens-shirts/Gigabyte%20Aorus%20Men%20Tshirt/1.png",
        "https://cdn.dummyjson.com/products/images/mens-shirts/Gigabyte%20Aorus%20Men%20Tshirt/2.png",
        "https://cdn.dummyjson.com/products/images/mens-shirts/Gigabyte%20Aorus%20Men%20Tshirt/3.png",
        "https://cdn.dummyjson.com/products/images/mens-shirts/Gigabyte%20Aorus%20Men%20Tshirt/4.png"
      ],
      "thumbnail": "https://cdn.dummyjson.com/products/images/mens-shirts/Gigabyte%20Aorus%20Men%20Tshirt/thumbnail.png",
      "qty": 1,
      "size": 2
    }
  ]
}

###
GET http://localhost:5000/api/order
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjY0NzE0MzRiM2EwZGU4ODRkMWM4ZjkiLCJpYXQiOjE3MjA1NDg1OTUsImV4cCI6MTcyMDU0ODY1NX0.EPJpW980W-gZewsxT9P4rV_mwM5kEs_dNjX6p4CKRUw

###

GET http://localhost:5000/api/order/668d7d27b5e48644d830dfc6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjY0NzE0MzRiM2EwZGU4ODRkMWM4ZjkiLCJpYXQiOjE3MjA1NDg2OTksImV4cCI6MTcyMDU0ODc1OX0.oDuevXQKow1Lkh2wB1m-YSCA1JF3S7-6Ap0CGY075yc

###

DELETE http://localhost:5000/api/order/668e4936ef5c0f59942e68de
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjY0NzE0MzRiM2EwZGU4ODRkMWM4ZjkiLCJpYXQiOjE3MjExNTQxNDAsImV4cCI6MTcyMTE1NDQ0MH0.0VrJu7fvXcIgMd_QwijXMBzxBXsiK-p5KH6hI2_KNpo


###

GET http://localhost:5000/api/favorite
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjY0NzE0MzRiM2EwZGU4ODRkMWM4ZjkiLCJpYXQiOjE3MjA4MTQ4MDgsImV4cCI6MTcyMDgxNTEwOH0.D8KMgiQOQqT7xFIXTNgim_tNViflwpbQEp4sTuVnF-U

###

POST http://localhost:5000/api/favorite
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjY0NzE0MzRiM2EwZGU4ODRkMWM4ZjkiLCJpYXQiOjE3MjA4MTQ0ODMsImV4cCI6MTcyMDgxNDc4M30.6_Fk4hy-5HVodxEnGt4YZmjcc-K_e08mUqZjrho0maA

###
PUT http://localhost:5000/api/favorite
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjY0NzE0MzRiM2EwZGU4ODRkMWM4ZjkiLCJpYXQiOjE3MjA4MTQ0ODMsImV4cCI6MTcyMDgxNDc4M30.6_Fk4hy-5HVodxEnGt4YZmjcc-K_e08mUqZjrho0maA

{
  "products": [
    {
      "id": 84,
      "title": "Gigabyte Aorus Men Tshirt",
      "description": "The Gigabyte Aorus Men Tshirt is a cool and casual shirt for gaming enthusiasts. With the Aorus logo and sleek design, it's perfect for expressing your gaming style.",
      "category": "mens-shirts",
      "price": 24.99,
      "discountPercentage": 12.6,
      "rating": 4.95,
      "stock": 64,
      "tags": [
        "clothing",
        "men's t-shirts"
      ],
      "brand": "Gigabyte",
      "sku": "QA703Y60",
      "weight": 2,
      "dimensions": {
        "width": 8.54,
        "height": 23.52,
        "depth": 5.66
      },
      "warrantyInformation": "1 month warranty",
      "shippingInformation": "Ships in 1 week",
      "availabilityStatus": "In Stock",
      "reviews": [
        {
          "rating": 4,
          "comment": "Highly recommended!",
          "date": "2024-05-23T08:56:21.623Z",
          "reviewerName": "Logan Lawson",
          "reviewerEmail": "logan.lawson@x.dummyjson.com"
        },
        {
          "rating": 4,
          "comment": "Great value for money!",
          "date": "2024-05-23T08:56:21.623Z",
          "reviewerName": "Logan Lawson",
          "reviewerEmail": "logan.lawson@x.dummyjson.com"
        },
        {
          "rating": 5,
          "comment": "Great value for money!",
          "date": "2024-05-23T08:56:21.623Z",
          "reviewerName": "Oscar Powers",
          "reviewerEmail": "oscar.powers@x.dummyjson.com"
        }
      ],
      "returnPolicy": "30 days return policy",
      "minimumOrderQuantity": 4,
      "meta": {
        "createdAt": "2024-05-23T08:56:21.623Z",
        "updatedAt": "2024-05-23T08:56:21.623Z",
        "barcode": "3072645939073",
        "qrCode": "https://assets.dummyjson.com/public/qr-code.png"
      },
      "images": [
        "https://cdn.dummyjson.com/products/images/mens-shirts/Gigabyte%20Aorus%20Men%20Tshirt/1.png",
        "https://cdn.dummyjson.com/products/images/mens-shirts/Gigabyte%20Aorus%20Men%20Tshirt/2.png",
        "https://cdn.dummyjson.com/products/images/mens-shirts/Gigabyte%20Aorus%20Men%20Tshirt/3.png",
        "https://cdn.dummyjson.com/products/images/mens-shirts/Gigabyte%20Aorus%20Men%20Tshirt/4.png"
      ],
      "thumbnail": "https://cdn.dummyjson.com/products/images/mens-shirts/Gigabyte%20Aorus%20Men%20Tshirt/thumbnail.png"
    },
    {
      "id": 84,
      "title": "Gigabyte Aorus Men Tshirt",
      "description": "The Gigabyte Aorus Men Tshirt is a cool and casual shirt for gaming enthusiasts. With the Aorus logo and sleek design, it's perfect for expressing your gaming style.",
      "category": "mens-shirts",
      "price": 24.99,
      "discountPercentage": 12.6,
      "rating": 4.95,
      "stock": 64,
      "tags": [
        "clothing",
        "men's t-shirts"
      ],
      "brand": "Gigabyte",
      "sku": "QA703Y60",
      "weight": 2,
      "dimensions": {
        "width": 8.54,
        "height": 23.52,
        "depth": 5.66
      },
      "warrantyInformation": "1 month warranty",
      "shippingInformation": "Ships in 1 week",
      "availabilityStatus": "In Stock",
      "reviews": [
        {
          "rating": 4,
          "comment": "Highly recommended!",
          "date": "2024-05-23T08:56:21.623Z",
          "reviewerName": "Logan Lawson",
          "reviewerEmail": "logan.lawson@x.dummyjson.com"
        },
        {
          "rating": 4,
          "comment": "Great value for money!",
          "date": "2024-05-23T08:56:21.623Z",
          "reviewerName": "Logan Lawson",
          "reviewerEmail": "logan.lawson@x.dummyjson.com"
        },
        {
          "rating": 5,
          "comment": "Great value for money!",
          "date": "2024-05-23T08:56:21.623Z",
          "reviewerName": "Oscar Powers",
          "reviewerEmail": "oscar.powers@x.dummyjson.com"
        }
      ],
      "returnPolicy": "30 days return policy",
      "minimumOrderQuantity": 4,
      "meta": {
        "createdAt": "2024-05-23T08:56:21.623Z",
        "updatedAt": "2024-05-23T08:56:21.623Z",
        "barcode": "3072645939073",
        "qrCode": "https://assets.dummyjson.com/public/qr-code.png"
      },
      "images": [
        "https://cdn.dummyjson.com/products/images/mens-shirts/Gigabyte%20Aorus%20Men%20Tshirt/1.png",
        "https://cdn.dummyjson.com/products/images/mens-shirts/Gigabyte%20Aorus%20Men%20Tshirt/2.png",
        "https://cdn.dummyjson.com/products/images/mens-shirts/Gigabyte%20Aorus%20Men%20Tshirt/3.png",
        "https://cdn.dummyjson.com/products/images/mens-shirts/Gigabyte%20Aorus%20Men%20Tshirt/4.png"
      ],
      "thumbnail": "https://cdn.dummyjson.com/products/images/mens-shirts/Gigabyte%20Aorus%20Men%20Tshirt/thumbnail.png"
    }
  ]
}






