GET http://localhost:5000/api/auth


###

POST http://localhost:5000/api/auth
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjY0NzE0MzRiM2EwZGU4ODRkMWM4ZjkiLCJpYXQiOjE3MjAyODI1NDEsImV4cCI6MTcyMDI4MjYwMX0.86lG-Qo690-wjYcXMYLq3RG-SU9tzQSb68_TB1YaeaU

###

POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "email": "nguyentuan22072004@gmail.com",
  "password": "tuan",
  "firstname": "tuan",
  "lastname": "nguyen",
  "address": {
    "country": "vietnam",
    "city": "ha noi",
    "province": "dong anh",
    "detail": "xom nguyen"
  }
}

###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "nguyentuan22072004@gmail.com",
  "password": "tuan"
}

###

POST http://localhost:5000/api/auth/token
Content-Type: application/json

{
    "refreshToken" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjY0NzE0MzRiM2EwZGU4ODRkMWM4ZjkiLCJpYXQiOjE3MTkxNTM4NzgsImV4cCI6MTcxOTI0MDI3OH0.8lkhxE6QkxXerMbKCjxwttsMHCUrdH4hfrO30tM7IGs"
}

###
DELETE http://localhost:5000/api/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjY0NzE0MzRiM2EwZGU4ODRkMWM4ZjkiLCJpYXQiOjE3MjA0MzE1MjksImV4cCI6MTcyMDQzMTU4OX0.f4XrKIBv0NEDTByQya6nsL2SrqzN3enZy4rUZmC1djw

###

POST http://localhost:5000/api/cart
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjY0NzE0MzRiM2EwZGU4ODRkMWM4ZjkiLCJpYXQiOjE3MTc5NDk2NTksImV4cCI6MTcxNzk1MzI1OX0.JBeTrWkwlrm5nRmKbNbE8DUK52-cxPrBA9u_sS1Nilo

###

GET http://localhost:5000/api/cart
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjY0NzE0MzRiM2EwZGU4ODRkMWM4ZjkiLCJpYXQiOjE3MTkwODQ4MDIsImV4cCI6MTcxOTA4ODQwMn0.L2hsBnz2WWmhwBIWNAZKgG6MQPI-zMHxBB94uxCesxc

###

PUT http://localhost:5000/api/cart
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjY0NzE0MzRiM2EwZGU4ODRkMWM4ZjkiLCJpYXQiOjE3MjAxMjQwOTksImV4cCI6MTcyMDEyNDE1OX0.bYwyJjtXNp49Wg7WXh2rdSLiOvZa07E9PaYzzVqwT_M

{
  "products":   [
    {
      "id": 1,
      "quantity": 2,
      "size": "S"
    },
    {
      "id": 2,
      "quantity": 2,
      "size": "S"
    },
    {
      "id": 4,
      "quantity": 11,
      "size": "S"
    }
  ]
}

###
DELETE http://localhost:5000/api/cart
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjY0NzE0MzRiM2EwZGU4ODRkMWM4ZjkiLCJpYXQiOjE3MTc5NDk2NTksImV4cCI6MTcxNzk1MzI1OX0.JBeTrWkwlrm5nRmKbNbE8DUK52-cxPrBA9u_sS1Nilo


### 

GET http://localhost:5000/api/order


###
POST http://localhost:5000/api/order
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjY0NzE0MzRiM2EwZGU4ODRkMWM4ZjkiLCJpYXQiOjE3MjA1NDg5MTUsImV4cCI6MTcyMDU0ODk3NX0.Li9kPnz2UymB10SoigZVUy6u5SsJEZ1tSfqtjcjjW14

{
  "payment": "CASH" ,
  "address": {
    "country": "vietnam",
    "city": "ha noi",
    "province": "dong anh",
    "detail": "xom nguyen"
  },
  "products":  [
    {
      "id": 4,
      "quantity": 6
    },
    {
      "id": 9,
      "quantity": 2
    },
    {
      "id": 12,
      "quantity": 11
    }
  ]

  
}

###
GET http://localhost:5000/api/order
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjY0NzE0MzRiM2EwZGU4ODRkMWM4ZjkiLCJpYXQiOjE3MjA1NDg1OTUsImV4cCI6MTcyMDU0ODY1NX0.EPJpW980W-gZewsxT9P4rV_mwM5kEs_dNjX6p4CKRUw

###

GET http://localhost:5000/api/order/668d7d27b5e48644d830dfc6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjY0NzE0MzRiM2EwZGU4ODRkMWM4ZjkiLCJpYXQiOjE3MjA1NDg2OTksImV4cCI6MTcyMDU0ODc1OX0.oDuevXQKow1Lkh2wB1m-YSCA1JF3S7-6Ap0CGY075yc

###

DELETE http://localhost:5000/api/order/666a49b9356e0704e126c1fb
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjY0NzE0MzRiM2EwZGU4ODRkMWM4ZjkiLCJpYXQiOjE3MTgyNDY4MTksImV4cCI6MTcxODI1MDQxOX0.VRmGl4Y0Uwa1aawDxEZnPDiv2fbx5VsEn5Qd0JFv6QM









